- src/components/Component.js
- src/components/map/Map.tsx
- src/context.tsx
- src/httpClient.ts
- src/metaAnalysis.ts
- src/types.ts
Adapted AirtableRecord type to reflect updated airtable schema, updated processing of http response, made all filters able to store multiple values, updated filtering and meta analysis logic to support updated schemas.
> WEB-15: Support Updated Airtable Schema

- src/App.css
- src/App.tsx
Temporary changes to the website to show our support for the black community
> #ShutDownSTEM

- src/components/charts/Charts.tsx
- src/components/map/Map.tsx
- src/components/sidebar/left-sidebar/CountryList.tsx
- src/components/sidebar/left-sidebar/TotalStats.tsx
- src/components/sidebar/right-sidebar/Filters.tsx
- src/components/sidebar/right-sidebar/LastUpdated.tsx
- src/components/sidebar/right-sidebar/RightSidebar.css
- src/context.tsx
- src/httpClient.ts
- src/metaAnalysis.ts
- src/tests/context.test.ts
- src/tests/metaAnalysis.test.ts
- src/tests/testData.ts
- src/types.ts
- src/utils/mapUtils.ts
- src/utils/translate/en.json
#92 --> specimen type filter is pretty straightforward
#100 --> read this ticket carefully to understand intended behaviour for include in n
> Specimen type filter and "include in n" behaviour

- src/components/pages/About.tsx
Added newest helpers to page credits.
> Added new contributers

- src/context.tsx
- src/types.ts
> Fix regeneration of filter options

- src/App.css
- src/components/sidebar/left-sidebar/TotalStats.tsx
- src/utils/mapUtils.tsx
- Titles font size increased globally.
- Padding adjusted for "Summary Statistics" title on left bar.
- Country font size in popup increased.
- The final popup section now omits the bottom border line.
> Ui clean up

- src/App.tsx
- src/components/charts/Charts.tsx
- src/context.tsx
- src/types.ts
updated references tab:
- Make sure the analyze tab popup only appears once per "session"
- /Dashboard should redirect to /Explore
> redirect dashboard to explore for bookmarked users

- src/components/pages/About.tsx
- src/utils/translate/en.json
What’s the difference between a guitar and a fish?
**You can’t tuna fish.**
> fixed Jonathan's bio, added Bruce

- src/components/charts/Charts.tsx
- src/context.tsx
Dependent on the following backend PR: https://github.com/serotracker/iit-backend/pull/91/files
> Readd analyze options

- src/App.css
- src/components/pages/Dashboard/Analyze.tsx
- src/components/pages/Dashboard/Explore.tsx
- src/components/shared/MaintenanceModal.tsx
- src/components/shared/shared.scss
- src/constants.ts
- src/utils/translate/en.json
i made modal for when things need to go down cuz we updating stuff in the back and front and ya know it be like that sometimes.
> Maintenance modal

- src/components/pages/Dashboard/Explore.tsx
- src/components/sidebar/right-sidebar/Filters.tsx
- src/components/sidebar/right-sidebar/SectionHeader.tsx
- src/components/sidebar/right-sidebar/datepicker/Datepicker.tsx
- src/utils/translate/en.json
Update datepicker UI and verbiage
Fix explore spinner loading
> Minor datepicker fixes

- src/components/shared/NavBar.tsx
Fixed off page nav bar buttons
> navbar fix

- src/components/map/Legend.css
> Make legend items smaller font size (mobile)

- src/components/map/Map.tsx
- src/httpClient.ts
> Add sampling dates to pin popup

- src/components/pages/About.tsx
Updated team names on About page! Sorry about all the lint changes, if it's an issue I can try to find a workaround.
Removed 
- Joanna Chen
Added
- Sean D'Mello
- Mercedes Yanes
- Sara Perlman-Arrow
- Prannoy Lal
- Lucia Otero Varela
- Divine Tanyingoh
- Noel Loo
> Updated team names

- src/components/pages/About.tsx
Quick fix to the About Page. The "People and Contact Info" spreadsheet doesn't list if team members are part of Private Sector, so I thought Sean D'Mello was a part of the Research team. Updated so he's a part of the Private Sector team!
> Update Sean D'Mello to Private Sector

- src/App.tsx
- src/components/shared/TableauEmbed.tsx
- src/constants.ts
- Adds Canadian Dashboard Tableau prototype (viewable at the /Canada URL, no visual entry point from the main site for now)
- Fixes double scrollbar issues
- Refactors page routing
- https://airtable.com/tbli2lWQHAqBa6ZcI/viwWvxb27XGuziw4c/recz3tBozneEUmRVS 
- Visited /Canada and /Analyze tabs and ensured that tableau vizzes looked good & contained the right content
- General regression testing (click through all pages, try switching between pages, etc)
No.
> Cad dash mock

- src/components/pages/Data.tsx
- src/utils/translate/en.json
- src/utils/translate/fr.json
Adds a one-liner to our Data page with links to our Manuscript Appendix and Dashboard SOP. This can help users find more context and information behind our data until we create a more long term solution for our data dictionary.
[Update data page to include SOP and Manuscript Appendix](https://airtable.com/tbli2lWQHAqBa6ZcI/viwTYqtBDdt3Wt3Yo/recUaaManRlzUMPBy?blocks=hide)
**English:**
**French:**
- Tested links were working correctly and that appearance was as expected
- Tested French and English translations 
Nope!
> Data dict super MVP

- src/context.tsx
- src/types.ts
Cleaned up some of the unused variables in React Context. Data page state variables must be added when filters are added to that page. 
https://airtable.com/tbli2lWQHAqBa6ZcI/viw8Ro4zYPYcBGXRw/recjrEU9Ba07eYuEe?blocks=hide
No UI changes, everything should work normally. 
Just tested around the website locally to see if any functionality was broken.
Nope.
> Cleaned up React Context

- .gitignore
Adds `vscode/`, `.env`, `load-dotenv.sh` to gitignore
None
N/A
Not necessary
No
> add to gitignore

- src/components/map/Layers/StudyPins.tsx
- src/components/map/MapConfig.ts
- src/utils/GeoJsonGenerator.tsx
- src/utils/usePrevious.ts
Adds a visual indication of which pin in selected when I user clicks, helpful in dense pin clusters. Also fixed a bug where pin feature IDs where no being correctly assigned.
Original ticket may have been deleted or lost, I created a fresh one:
https://airtable.com/tbli2lWQHAqBa6ZcI/viw8Ro4zYPYcBGXRw/rec54MPh0plWwes6e?blocks=hide
> Study Pin Selection Focus

- .github/workflows/deploy-staging-1.yml
- .github/workflows/deploy-staging-2.yml
- .github/workflows/deploy-staging-3.yml
On-demand deploy
https://airtable.com/tbli2lWQHAqBa6ZcI/viwSkpZmJR8D99kla/recGXh7zHsgqWtGBE?blocks=hide
Tested with `staging-1` branch. Deployed here: http://serotracker-staging-1.herokuapp.com/en/Explore
> On-demand deploy

- src/constants.ts
> Remove maintenance banner

- src/utils/translate/en.json
- src/utils/translate/fr.json
> Fix Data Dictionary Typos

- README.md
Update README.
https://airtable.com/tbli2lWQHAqBa6ZcI/viwSkpZmJR8D99kla/recbKtLwhee97VY07?blocks=hide
No
> Add CI/CD details

- src/App.tsx
- src/components/shared/TableauEmbed.tsx
- src/constants.ts
Modified tableauEmbed component so that it can support multiple languages, added french version of Canadian analyze tab
https://airtable.com/tbli2lWQHAqBa6ZcI/viwWvxb27XGuziw4c/recFSoCb16lzy3Go3?blocks=bipIkdtYHmboUfJut
Smoke tests
N/A
They've been included in tableau, no need to handle in code
> Add french version of Canadian tableau dash

- src/constants.ts
> throw up maintenance modal

- src/constants.ts
This reverts commit c75e2ae33d5e82b3093cdedff9287644c5cf0522.
> Revert "throw up maintenance modal"

- src/components/sidebar/left-sidebar/TotalStats.tsx
- src/utils/translate/en.json
- src/utils/translate/fr.json
Updated Explore page to be clearer to users as per this [Slack discussion](https://serotracker.slack.com/archives/C01LF2V72FN/p1619540612032600).
https://airtable.com/tbli2lWQHAqBa6ZcI/viwTYqtBDdt3Wt3Yo/rec0Mwk38OwpzEfPQ?blocks=hide
Click around locally and check that everything looks accurate!
Nope!
Yes, many - all have been documented in the #translate-fr Slack channel
> QoL / wording improvements to explore

- src/utils/translate/en.json
- src/utils/translate/fr.json
Readds some missing translations (country hover modal)
https://airtable.com/tbli2lWQHAqBa6ZcI/viwWvxb27XGuziw4c/recNV342Ah205SNja?blocks=bipIkdtYHmboUfJut
Yes
> Readd missing translations

- src/constants.ts
> Add maintenance modal

- src/constants.ts
> Removed maintenance mode

- pull_request_template.md
- src/App.tsx
- src/components/map/Popups/StudyPopup.tsx
- src/components/shared/references/StudiesTable.tsx
- src/components/shared/references/StudyDetailsModal.tsx
- src/constants.ts
- src/types.ts
1. Fixes 'undefined' for N field on study modal
2. Adds updated Tableau embed link for Canadian english page and changes iFrame height
3. Updates pull request md with instructions for QA testing PR
- https://airtable.com/tbli2lWQHAqBa6ZcI/viw8Ro4zYPYcBGXRw/rech2MiTF1I0vkMwf?blocks=hide
- https://airtable.com/tbli2lWQHAqBa6ZcI/viw8Ro4zYPYcBGXRw/recySBHiGNdbnooyB?blocks=hide
- Checked N value in study modal for multiple estimates
- Checked Canadian page and scrolled through tableau graphs
> fixing tableau embed, fixing null N, updating pull request template

- src/App.tsx
- src/PartnershipsConfig.ts
- src/utils/translate/en.json
- src/utils/translate/fr.json
Partnership changes to text and tableau embeds
> text and link changes

- src/components/pages/Partnerships/Partnerships.tsx
Resizes cad dash embeds
N/A
Notice lack of double scroll on both
Visual smoke test
N/A
N/A
- Map has pins …
> Resize cad dash embeds

- src/components/sidebar/right-sidebar/RightSidebar.css
Removes white space from bottom of the right sidebar
NA
old:
new:
manual
NA
NA
- Map has pins
- "terms of …
> removed the whitespace at the bottom of the right sidebar

- src/App.tsx
Request from Jordan to change height of analyze embed to reflect changes to the tableau dashboard
N/A
Smoke test
No
No
- Map has pins
- Data download link provides access to a …
> Change height of analyze embed

- src/components/pages/CookiePolicy.tsx
- src/components/pages/PrivacyPolicy.tsx
- src/components/pages/static.css
Cookie and privacy policy styling is broken on prod (check by clicking links from footer).
https://airtable.com/tbli2lWQHAqBa6ZcI/viwTYqtBDdt3Wt3Yo/recOVCXRAHO6YgTXM?blocks=hide
- Updated styles and classes used on iFrame (wanted to use HTML content but realized it doesn't update automatically)
- Nope!
- NOpe!
- Map has pins
- Check for double scrolling (the embed …
> Fixed broken cookie and privacy policy styling

- src/constants.ts
> remove maintenance modal

- src/constants.ts
Reverts serotracker/sero-can-webapp#275
> Revert "remove maintenance modal"

- src/constants.ts
Reverts serotracker/sero-can-webapp#278
> Revert "Revert "remove maintenance modal""

- src/App.tsx
- src/components/map/Layers/Countries.tsx
- src/components/map/Layers/StudyPins.tsx
- src/components/pages/Dashboard/Explore.tsx
- src/components/pages/Data.tsx
- src/components/shared/InformationIcon.tsx
- src/components/shared/InformationText.tsx
- src/components/sidebar/right-sidebar/Filters.tsx
- src/components/sidebar/right-sidebar/datepicker/Datepicker.tsx
- src/index.js
- src/utils/analyticsUtils.tsx
- src/utils/stateUpdateUtils.tsx
Adds the following improvements to google analytics tracking:
- Logs filter combinations instead of just individual filter events, incorporate date filter and WHO unity checkbox
- Logs opening up study modal, data FAQ panes
- Initializes GA tracker object earlier to ensure that event logs in useEffects work properly
https://airtable.com/appT8tnLbGJV6v81V/tbli2lWQHAqBa6ZcI/viwWvxb27XGuziw4c/recdjIklaXEkd6cUy?blocks=hide
N/A
Tested locally using the serotracker dev google analytics instance
N/A
N/A
- Map has pins
- Execute a Filter for Risk of bias, Sex, …
> Extend & improve google analytics coverage

- src/App.tsx
- src/context.tsx
- src/types.ts
Removed unsed restcountries.eu endpoint which was yielding due to service fees
https://airtable.com/appT8tnLbGJV6v81V/tbli2lWQHAqBa6ZcI/viwKscR1ZvgkUxVtA/recTT9kE3KUQ6jurg?blocks=bipIkdtYHmboUfJut
> Removed restcountries.eu endpoint

- src/constants.ts
Reverts serotracker/sero-can-webapp#279
> Revert "Revert "Revert "remove maintenance modal"""

- src/constants.ts
Reverts serotracker/sero-can-webapp#298
> Revert "Revert "Revert "Revert "remove maintenance modal""""

- src/components/sidebar/right-sidebar/Filters.tsx
- src/context.tsx
- src/types.ts
- src/utils/translate/en.json
- src/utils/translate/fr.json
This PR adds an antibody target filter under the "Test Information" section.
[Create filter for "antibody target"](https://airtable.com/appT8tnLbGJV6v81V/tbli2lWQHAqBa6ZcI/viwTYqtBDdt3Wt3Yo/recIeNQCDS0ftY98q?blocks=hide)
- Click the different options and waited to see if Explore page was filtered 
- Still need French translations
- Map has pins
- Check for double …
> Add antibody target filter

- src/components/pages/Publications/PublicationsConstants.ts
- src/utils/translate/en.json
- src/utils/translate/fr.json
> Add late october literature update report

- src/components/sidebar/right-sidebar/Filters.tsx
- src/context.tsx
- src/types.ts
- src/utils/translate/en.json
- src/utils/translate/fr.json
Removes specimen type filter from Filters tab on Explore page 
[Remove specimen type filter](https://airtable.com/appT8tnLbGJV6v81V/tbli2lWQHAqBa6ZcI/viwTYqtBDdt3Wt3Yo/recV8VcnKmgukJFkT?blocks=hide)
Visual inspection
Nope!
Nope!
- Map has pins
- …
> Remove specimen type filter

- src/components/pages/Partnerships/CanadaPartnership.tsx
- src/utils/translate/en.json
- src/utils/translate/fr.json
- CITF Partnerships Page Description - Use hyperlink instead of putting website text in brackets
https://airtable.com/appT8tnLbGJV6v81V/tbli2lWQHAqBa6ZcI/viwWvxb27XGuziw4c/recMU9OjKqCisGmVp?blocks=bip9X54YrLFYz3ycP
N/A
- Map has pins
- References table …
> CITF Partnerships Page Description - Use hyperlink instead of putting website text in brackets

- src/components/pages/Dashboard/Explore.tsx
- src/utils/translate/en.json
- src/utils/translate/fr.json
Added in a popup that comes up on the dashboard on mobile prompting users to use desktop instead for a better user experience. 
https://airtable.com/appT8tnLbGJV6v81V/tbli2lWQHAqBa6ZcI/viw2Kjofxz0J1dHD0/recODRthbXbO1k1cL?blocks=hide
NO
Yes
- Map has pins
- Click a FAQ for …
> added mobile popup

- src/httpClient.ts
Frontend changes to support the following PR: https://github.com/serotracker/iit-backend/pull/286 
https://airtable.com/appT8tnLbGJV6v81V/tbli2lWQHAqBa6ZcI/viwWvxb27XGuziw4c/reczHJuNDv6LRAzMq?blocks=bip9X54YrLFYz3ycP
Ran frontend locally against local backend running [this branch](https://github.com/serotracker/iit-backend/pull/286 ). Looked for the following:
- Correct numbers of records (both on initial load and upon application of filters)
- Presence of only primary estimates
- Expected speed improvements
https://github.com/serotracker/iit-backend/pull/286 
N/A
- Map has pins
- Select …
> Frontend changes to support removal of estimate prioritization

- .github/workflows/ci.yml
- .github/workflows/deploy-gh-pages.yml
I think github-actions updated the default node version used on their workflow runners. I updated our ci/cd to use a specific version of node that we know we can support.
- Map has pins
- Check that downloads are …
> Fixes Deploy/CI Jobs

- src/components/map/Layers/Countries.tsx
Fixed layers failing to load on legend click
https://airtable.com/appT8tnLbGJV6v81V/tbli2lWQHAqBa6ZcI/viwKscR1ZvgkUxVtA/rec9uCBEg78vkGYSg?
> Fixed layers failing to load on legend click

- src/components/pages/Data.tsx
- src/utils/translate/en.json
- src/utils/translate/fr.json
Wording fixes on data page
https://airtable.com/appT8tnLbGJV6v81V/tbli2lWQHAqBa6ZcI/viwWvxb27XGuziw4c/recQczU8xYioVWsyC?blocks=bip9X54YrLFYz3ycP
- Map has pins
- Data download link …
> Wording fixes on data page

- src/components/shared/TableauEmbed.tsx
- src/constants.ts
Adds support for french in analyze page.
https://airtable.com/appT8tnLbGJV6v81V/tbli2lWQHAqBa6ZcI/viwKscR1ZvgkUxVtA/recCHRznu1IjuiTHj?blocks=hide
le french analyze 🥖
> Analyze Page - French tableau

- src/components/pages/Publications/PublicationsConstants.ts
- src/utils/translate/en.json
- src/utils/translate/fr.json
Adds new biblio digest
- Map has pins
- Carousel is …
> Add december biblio digest

- .gitignore
- src/utils/translate/de.json
- src/utils/translate/en.json
- src/utils/translate/fr.json
- updated "where do we get data from"
- added "how often is data updated"
https://airtable.com/appT8tnLbGJV6v81V/tbli2lWQHAqBa6ZcI/viw2Kjofxz0J1dHD0/rec9w4yKrsZqx4QnJ?blocks=hide
Yes
- Map has pins
- Check that downloads …
> updated FAQ

- src/components/pages/Partnerships/CanadaPartnership.tsx
- src/constants.ts
Updated tableau links for analyze tab (EN, FR) & Canada partnerships page (EN only)
https://airtable.com/appT8tnLbGJV6v81V/tbli2lWQHAqBa6ZcI/viwd4wBtXMu3C2Caf/recStpUet1KII2CSm?blocks=bip9X54YrLFYz3ycP
- Map has pins
- …
> updated analyze (en, fr) and canada (en) links

- src/PartnershipsConfig.ts
> Update tableau links for Canadian tableau

- src/components/pages/About.tsx
- src/components/pages/Data.tsx
- src/components/pages/Publications/Publications.tsx
- src/components/pages/Publications/PublicationsConstants.ts
- src/constants.ts
- src/utils/translate/de.json
- src/utils/translate/en.json
- src/utils/translate/fr.json
- Moving Brett, Jordan and Prannoy to Alumni section
- Changing "References" in footer to "Data Table" because that is the title we use on the Data page
- Changing "Monthly Reports" to "Private Sector Reports" on the Publications page and in the footer
- Removing some periods and changing wording slightly in pub page descriptions
- https://airtable.com/appT8tnLbGJV6v81V/tbli2lWQHAqBa6ZcI/viwDpHWCgFagItSc6/recQwfCLejDRTtnUc?blocks=hide
- https://airtable.com/appT8tnLbGJV6v81V/tbli2lWQHAqBa6ZcI/viwDpHWCgFagItSc6/recZ24k5qCzwCRT25?blocks=hide
- https://airtable.com/appT8tnLbGJV6v81V/tbli2lWQHAqBa6ZcI/viwDpHWCgFagItSc6/rec3oyB8ZNnY2tQ0r?blocks=hide
- Map has pins
- …
> Small wording and styling fixes on Publications and About Page

- src/components/pages/About.tsx
- src/components/pages/Publications/PublicationsConstants.ts
- src/utils/translate/de.json
- src/utils/translate/en.json
- src/utils/translate/fr.json
- Added 3 new publications of ours to the publications page
- Changed description under "Research articles" on pubs page to also include pre prints
- Added the biblio digest from jan 14 to the publications page
- Moved noel to alumn
- Map has pins
- …
> Updating publications and about page

- src/components/pages/Partnerships/CanadaPartnership.tsx
- src/utils/translate/de.json
- src/utils/translate/en.json
- src/utils/translate/fr.json
- Decreasing size of tableau iframe to remove whitespace on the bottom
- Changing the capitalization of the english title of the map
- Changing the EN, DE, FR versions to use "Canada" instead of "NAME"
- Adding an additional sentence to CITF description to highlight modelling CITF site
- Changing CITF page title slightly
- Map has pins
- Check for double scrolling …
> Small fixes to partnerships page

- README.md
> Update README.md to include more details surrounding node setup

- src/components/pages/Publications/styles.scss
The borders for custom cards and items didnt match that of semantic UI. Changed the CSS to make all borders consistent. 
https://airtable.com/appT8tnLbGJV6v81V/tbli2lWQHAqBa6ZcI/viw2Kjofxz0J1dHD0/recPR2sgWM53CMJ69?blocks=hide
- Map has pins
- …
> updated all borders to match

- src/constants.ts
added the German translate link for the tableau on the analyse page. 
- Map has pins
- "terms of use" …
> added a link to the german translate

- src/components/pages/Publications/PrivateReportsCard.tsx
- src/components/pages/Publications/Publications.tsx
- src/components/pages/Publications/PublicationsConstants.ts
- src/components/pages/Publications/styles.scss
- src/types.ts
- src/utils/translate/de.json
- src/utils/translate/en.json
- src/utils/translate/fr.json
- Converted the monthly report from a list to a card carousel
- Compressed getCaarousel methods into a single method with a toggle for the differetn carousels instead of individual methods. 
https://airtable.com/appT8tnLbGJV6v81V/tbli2lWQHAqBa6ZcI/viw2Kjofxz0J1dHD0/rec1YKDUcgXv2K3PX?blocks=hide
- Map has pins
- Check for double scrolling (the embed scrolls within the …
> Monthly cards

- src/components/pages/Data.tsx
Just updating the "Our Protocol" link on our website to point to the new protocol.
https://airtable.com/appT8tnLbGJV6v81V/tbli2lWQHAqBa6ZcI/viw7XzWHQfwP7pqcV/recE8oJymWtIHBgY8?blocks=hide
- Map has pins
- Check that …
> Updated link on website to the new protocol

- src/components/pages/Publications/PublicationsConstants.ts
- src/utils/translate/de.json
- src/utils/translate/en.json
- src/utils/translate/fr.json
- adding biblio from april 7 and new publication from the team from feb 15
- Map has pins
- "terms of …
> Updating publications page

- src/components/shared/Footer/NewsletterEmailInput.tsx
> fixed typo

- src/components/pages/Publications/PublicationsConstants.ts
Added biblios up to the september newsletter
https://airtable.com/appT8tnLbGJV6v81V/tbli2lWQHAqBa6ZcI/viw2Kjofxz0J1dHD0/recKsCS5kAvcJHLet?blocks=hide
- Map has pins
- Data download …
> added last biblios up to sept newsletter

- src/components/pages/Publications/PublicationsConstants.ts
Added the sep 23 2022 literature update to the biblio section of the publications page (https://drive.google.com/file/d/1HN4e2lVkPeU3xHpC7fkK5Caj5vfu4MVh/view)
https://airtable.com/appT8tnLbGJV6v81V/tbli2lWQHAqBa6ZcI/viwFS5nE6gepmRwVB/rec9w7vdVcJKbhPpD?blocks=hide
- Map has pins
- …
> Sep 23 2022 Literature Update

- src/components/pages/Publications/PublicationsConstants.ts
Add details for the Oct. 21 Biblio release
https://airtable.com/appT8tnLbGJV6v81V/tbli2lWQHAqBa6ZcI/viwFS5nE6gepmRwVB/recnrwdUObDQHAQ97?blocks=hide
- Map has pins
- Data download link …
> Add Oct. 21 Biblio

- src/components/pages/static.css
Frequently asked questions was not being displayed with the correct color causing it to not be seen on the data page
https://airtable.com/appT8tnLbGJV6v81V/tbli2lWQHAqBa6ZcI/viwFS5nE6gepmRwVB/recjCb0LEKwRdLKPv?blocks=hide
- Map has pins
- References …
> FAQ missing

- src/components/pages/Publications/PublicationsConstants.ts
Added in a bunch of missing biblios
Checked all links and values on the website
- Map has pins
- "terms …
> Added in the biblios up to the one published on Jan 13th: total 3

- src/components/pages/Publications/PublicationsConstants.ts
Added in biblios
- Map has pins
- Carousel is …
> Added biblios generated in feb, mar, apr

- src/components/pages/Publications/PublicationsConstants.ts
This adds the May 08 biblio report.
https://drive.google.com/file/d/1iUZ9NZeHgjGFzokQD_EyQ9xHOtruQpvC/view?usp=sharing
N/A
N/A
- Map has pins
- Data download link provides access to a …
> Add May 08 Biblio Report

- src/components/pages/Publications/PublicationsConstants.ts
> 06/02/2023 Biblio

- src/components/map/Legend.tsx
- src/components/map/MapConfig.ts
- src/components/map/MapboxMap.tsx
> Map fix bandaid
