serotracker/sero-can-webapp

src/metaAnalysis.ts, src/tests/metaAnalysis.test.ts
Add compute overall number of tests aggregated in meta analysis functions, expose function to calculate pooled metrics for all supplied records.
#34
=> Updates to meta analysis functions

src/components/pages/About.tsx, src/components/pages/Data.tsx, src/components/sidebar/left-sidebar/LeftSidebar.tsx, src/components/sidebar/right-sidebar/LastUpdated.tsx, src/utils/translate/en.json
It would be great to put small PHAC, CITF, and UCalgary logos (the same ones on the About page) on the Dashboard page, per a request from CITF yesterday. These can go in the bottom left of the Explore tab.
To reflect the dates that our data is up to date until: let's use the verbage "Database Up to Date To". This applies on the dashboard (bottom right, replacing 'server last refreshed); and above the AirTable embed.
To get the above date, can we automatically get the date of the last report that has been included in the database? Scrape the airtable for the most recent PUBLICATION_DATE and use that as the date for the above. This will require a little back-end work, but not much.
Can we link to our Terms of Use right above our AirTable embed, or right beside the button that ultimately …
=> added people to about, changed verbiage around site

src/components/charts/Charts.css, src/components/charts/Charts.tsx, src/types.ts, src/utils/translate/en.json, src/utils/translate/fr.json
Analyze tab looks wonky when filter combinations that return no data are set by the user.
https://airtable.com/tbli2lWQHAqBa6ZcI/viw7Tba8QVTJ49F4v/reckRZBzQOxlvkvmd
Ran the webapp locally, visited analyze tab, added filters that should return no data.
https://github.com/serotracker/iit-backend/pull/152
=> No data analyze

src/components/sidebar/right-sidebar/Filters.tsx, src/utils/translate/en.json, src/utils/translate/fr.json
Replace "Country/Sovereignty/Region" with "Countries and Areas"
Locally ran and smoke tested
No.
=> Small nomenclature change for WHO compliance

src/httpClient.ts, src/types.ts
Changes of the following filter option names:
start_date --> sampling_start_date
end_date --> sampling_end_date
Simona's filter changes
=> sampling naming change

src/components/map/Layers/Countries.tsx, src/components/map/Layers/StudyPins.tsx, src/components/map/Legend.css, src/components/map/Legend.tsx, src/components/map/MapConfig.ts, src/components/map/MapboxMap.css, src/components/map/MapboxMap.tsx, src/context.tsx, src/types.ts, src/utils/translate/en.json, src/utils/translate/fr.json
The WHO feedback as per their email:
Legend : Given that the oPt is depicted using the “Country with seroprevalence estimates” grey, the corresponding item in the legend should read “Countries and areas with seroprevalence estimates”.
The “not applicable” grey item should be included
Summary statistics (top left side of the page): if the 73 “countries included” includes the oPt and other areas such as French Guyana, this should be changed to read “countries and areas included: 73” 
Jammu&Kashmir: the dotted line of control is missing
Aksai Chin: we would suggest avoiding to display the box reporting data for “China” when placing the cursor over Aksai Chin. This is because, as signaled by its colorization, this area is disputed.
Kenya/South Sudan border: the dashed triangle is missing …
=> Who map compliance mapbox

src/components/map/Layers/StudyPins.tsx
- Bug description per slack message: It seems initial load is the only time we are actually generating a study pins layer. When the user applies filters, we simply apply a Mapbox client side filter on the study pins layer to only include study pins with IDs matching the IDs returned from our API. The problem with this approach is that it assumes that the records in the initial response is a superset of the records from any filtered response. This is a false assumption due to estimate prioritization (EP). EP aims to select the most representative estimate for a given study given certain filter params. As such, EP may select some top level estimate for the study when no filters are applied, but select a different estimate to represent that study when we provide a filter.
- Solution: Use …
=> Fix Filtering

src/utils/analyticsUtils.tsx
Google Analytics events were not being sent to our dashboard for over a year because of a small mistake we missed...
https://airtable.com/tbli2lWQHAqBa6ZcI/viwTYqtBDdt3Wt3Yo/rechJLXHFeThfYOi8?blocks=hide
- Download Google Analytics debugger
- Set local environment variable to include our Google Analytics project tracking id
- Look at dashboard while clicking around locally
- Nope!
- Nope!
=> Fixed Google Analytics events not sending to dashboard

src/components/map/Popups/StudyPopup.tsx, src/components/shared/references/StudiesTable.tsx, src/components/shared/references/StudyDetailsModal.tsx, src/types.ts
- Seroprevalence field was showing as N/A for all study modals
- This was because the backend field is called serum_pos_prevalence but the frontend was calling record.seroprevalence
- Looked at study modals with and without different filters
=> Bug fix - all seroprevalence estimates showing as NULL on study modal

src/App.tsx, src/components/map/Legend.css, src/components/map/Legend.tsx, src/components/pages/Dashboard/Explore.tsx, src/components/shared/InformationIcon.tsx, src/components/sidebar/right-sidebar/Filters.css, src/components/sidebar/right-sidebar/Filters.tsx, src/components/sidebar/right-sidebar/RightSidebar.tsx, src/components/sidebar/right-sidebar/datepicker/Datepicker.tsx, src/context.tsx, src/httpClient.ts, src/types.ts, src/utils/stateUpdateUtils.tsx, src/utils/translate/en.json, src/utils/translate/fr.json
- Adds unity studies checkbox and /Unity view (same as explore but with checkbox checked off by default)
- Changes filters and filter options data models to use arrays instead of sets (sets were an artifact from when we were doing filtering logic on the frontend)
- Removes some unnecessary code (dataPageState, some types that were not being used, API call that's not being used, unnecessary dispatches)
https://airtable.com/tbli2lWQHAqBa6ZcI/viwWvxb27XGuziw4c/recGnymO05NXQZDqX?blocks=bipIkdtYHmboUfJut
Smoke test
Yes, but PR has been merged
Yes, will include them all once we figure out exactly what text we want to show
=> Unity studies filter

src/App.tsx
Readds the /Unity route, which I suspect was removed when fixing a merge conflict
N/A
N/A
N/A
N/A
N/A
- Map has pins
- …
=> Readd /Unity route (removed by merge conflict)

src/components/sidebar/left-sidebar/LeftSidebar.tsx
Added download button to explore page, removed unneeded descriptive text as per Jordano's request
=> Explore - Download button

src/components/pages/Publications/PublicationsConstants.ts, src/utils/translate/en.json, src/utils/translate/fr.json
Adds NYT and Economist articles
N/A
Local test
N/A
- Map has pins
- Cards all …
=> Added NYT and Economist articles

src/components/pages/Publications/Publications.tsx, src/components/pages/Publications/styles.scss
The spacing on the publications page was broken. 2 line fix for that
NA
back to normal:
Visual test
no
no
- Map has pins
- …
=> fixed a spacing issue in the publications page

src/components/sidebar/right-sidebar/Filters.tsx
- Updated filters to pull from updated filter options endpoint 
https://airtable.com/tbli2lWQHAqBa6ZcI/viwTYqtBDdt3Wt3Yo/rec5XzyfWRX4GQ3N4?blocks=hide
- Map has pins
- Data download …
=> Add airtable filter ordering for population_group

src/components/map/Popups/StudyPopup.tsx
- when the vaccination policy is high i.e. vaccinations available to broader population it just says VaccinationPolicy
- variable name was wrong, it should be VaccinationPolicyHigh instead
- Map has pins
- Check that …
=> Bug fix for vaccination policy high flag

src/components/pages/About.tsx, src/components/pages/Publications/PublicationsConstants.ts, src/utils/translate/en.json, src/utils/translate/fr.json
Links on about pages were not opening in a new tab. 
Added in the november literature report
https://airtable.com/appT8tnLbGJV6v81V/tbli2lWQHAqBa6ZcI/viw2Kjofxz0J1dHD0/recFPLl9d5J04xF2m?blocks=hide
yes yes
- Map has pins …
=> About page links

src/utils/translate/fr.json
This PR translates all filter options to French (there were some stragglers that were in still in English) as a result of QA.
[Bug fix: Translate all filter options to French](https://airtable.com/appT8tnLbGJV6v81V/tbli2lWQHAqBa6ZcI/viwTYqtBDdt3Wt3Yo/recJTB5zdrGlcusR0?blocks=hide)
Source type:
Overall risk of bias:
Sex:
Age:
Test type:
Manual check on local
Nope!
Whole PR is French translations!
- Map has pins
- …
=> Bug fix: Translate all filter options to French

src/constants.ts
Fixes order of footer links to reflect order in actual pages
https://airtable.com/appT8tnLbGJV6v81V/tbli2lWQHAqBa6ZcI/viwKscR1ZvgkUxVtA/rec9vWcScRx7nWWoF?blocks=hide
Before:
After:
=> Footer - Link order fixes

src/PartnershipsConfig.ts, src/components/partnerships/PartnershipsMap.tsx
Fixes CITF map positioning and adds loading state (only applicable on desktop)
https://airtable.com/appT8tnLbGJV6v81V/tbli2lWQHAqBa6ZcI/viw4trdGlGgVxhdcj/recemgwEfOz5D0wAX?blocks=bip9X54YrLFYz3ycP
Old CITF map positioning:
New CITF map positioning:
Tested locally against prod backend. Ensured no regressions on the CITF page. 
N/A
- Map has pins
- Check for double …
=> Fix CITF map positioning and add loading state 

src/components/map/Layers/StudyPins.tsx, src/components/map/Popups/StudyPopup.tsx, src/httpClient.ts, src/types.ts, src/utils/translate/translateService.ts, src/utils/utils.tsx
- Translates study modal date and population group
- Removes unnecessary array -> set conversions
- Fixes bug where after switching languages, multiple study modals are rendered on click (see this [commit](https://github.com/serotracker/sero-can-webapp/commit/b3afde5dcbe4b6f10be2ac691938b5a6dfeed962))
Note about the last bugfix: The bug was being caused by us registering multiple on click events every time `state.language` was updated. Thus in order to resolve the issues, we needed to find a way to write the useEffect that generated the study popup without having it depend on `state.language`. The bug and fix are a but confusing, open to suggestions on better fixes.
- Map has pins
- Country Modal …
=> Translate Study Modal Date & Pop Group

src/components/pages/Publications/PublicationsConstants.ts
- Link to dec 17 biblio was pointing to Nov 26
- Map has pins
- Cards all load …
=> Fixing biblio link for Dec 17

src/components/pages/Data.tsx, src/components/shared/DownloadButton.tsx, src/components/sidebar/left-sidebar/LeftSidebar.tsx, src/sass/app.scss, src/types.ts
Fixes tech debt with download buttons:
- Adds types
- Fixes positioning of popup
- Fixes margins in styling
[Address tech debt with Github button download ticket](https://airtable.com/appT8tnLbGJV6v81V/tbli2lWQHAqBa6ZcI/viwTYqtBDdt3Wt3Yo/recpBHWgZYDnanVif?blocks=hide)
Nope!
Nope!
- Map has pins
- Click …
=> Address tech debt with Github button download ticket

src/App.tsx, src/components/pages/Explore/Explore.tsx, src/components/shared/NewsletterPopup.tsx, src/sass/components/shared.scss
Added in subscription popu
- Shows up 30 seconds after user visits the website for the second time
- added in local storage vars to track if this is a first visit, and or if the user has seen and closed the sub popup or not.
https://airtable.com/appT8tnLbGJV6v81V/tbli2lWQHAqBa6ZcI/viw2Kjofxz0J1dHD0/recL30w8N78X6tHep?blocks=hide
Tested the setting and unseting of variabels n many pages.
Tested interaction and timing of popup and made sure the functional flow is as expected. 
- Map has pins
- Check the …
=> Subscription popup

src/components/pages/Publications/PublicationsConstants.ts, src/utils/translate/de.json, src/utils/translate/en.json, src/utils/translate/fr.json
- Adding one new paper and march biblio to pubs page and fixing year of previous biblio card from 2021 to 2022
- Map has pins
- Data download link provides access to a downloadable …
=> Adding new paper and biblio to pubs page

src/components/map/Popups/StudyPopup.tsx, src/utils/translate/de.json, src/utils/translate/en.json, src/utils/translate/fr.json
- Changing the arrow between the dates on the study modal to the word "to"
- Fixing a german word that wasn't translated
- Map has pins
- Data download link provides access to a …
=> Changing "-->" to "to" between dates on study modal

src/components/pages/Partnerships/CanadaPartnership.tsx, src/components/shared/TableauEmbed/TableauEmbed.tsx
- The translations on the partnerships page were offset by one. This fixes that and syncs up the translations. 
https://airtable.com/appT8tnLbGJV6v81V/tbli2lWQHAqBa6ZcI/viw2Kjofxz0J1dHD0/recce1i0nRQsHBudz?blocks=hide
tried rep[roducing the error. could not reproduce.
Tried alternative ways to reproduce error. could not reproduce. 
- Map has pins
- Check for double …
=> added differentiating factor in key

src/components/pages/static.css
The Explore.tsx component has a height of 100vh, we need to reduce that to account for the header so that it does not cut out the page
https://airtable.com/appT8tnLbGJV6v81V/tbli2lWQHAqBa6ZcI/viwFS5nE6gepmRwVB/rec8p3hYMDlHfiLnc?blocks=hide
- Open home page of the serotracker web app
- Change window size and notice the explore component changes with window and remains within the view of the page without scrolling
- Map has pins
- Check each footer item …
=> Explore page height cutoff

src/App.tsx, src/components/shared/Footer/Footer.tsx, src/components/sidebar/left-sidebar/LeftSidebar.tsx, src/context.tsx, src/httpClient.ts, src/types.ts, src/utils/translate/de.json, src/utils/translate/en.json, src/utils/translate/fr.json
Updated UI to display most recent pub date as well as the last updated date
- Map has pins
- "terms of …
=> updated text and added new text
